---
# Broker Default Variables

pulsar_version: "3.0.0"
pulsar_cluster_name: "pulsar-aws-lab"

broker_heap_size: "1G"
broker_direct_memory_size: "512M"
broker_managed_ledger_cache_size_mb: 256
broker_managed_ledger_default_ensemble_size: 3
broker_managed_ledger_default_write_quorum: 3
broker_managed_ledger_default_ack_quorum: 2
broker_default_retention_time_minutes: 0
broker_default_retention_size_mb: 0
broker_max_unacked_messages_per_consumer: 50000
broker_max_unacked_messages_per_subscription: 200000
broker_dispatch_throttling_rate_per_topic_in_msg: 0
broker_dispatch_throttling_rate_per_topic_in_byte: 0
