---
# ZooKeeper Installation and Configuration

- name: Create Pulsar directory
  file:
    path: /opt/pulsar
    state: directory
    mode: '0755'

- name: Download Pulsar binary
  get_url:
    url: "https://archive.apache.org/dist/pulsar/pulsar-{{ pulsar_version }}/apache-pulsar-{{ pulsar_version }}-bin.tar.gz"
    dest: "/tmp/apache-pulsar-{{ pulsar_version }}-bin.tar.gz"
    timeout: 300

- name: Extract Pulsar binary
  unarchive:
    src: "/tmp/apache-pulsar-{{ pulsar_version }}-bin.tar.gz"
    dest: /opt/pulsar
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: /opt/pulsar/bin/pulsar

- name: Create ZooKeeper data directory
  file:
    path: "{{ zookeeper_data_dir }}"
    state: directory
    mode: '0755'

- name: Create ZooKeeper myid file
  copy:
    content: "{{ zk_id }}"
    dest: "{{ zookeeper_data_dir }}/myid"
    mode: '0644'

- name: Configure ZooKeeper
  template:
    src: zoo.cfg.j2
    dest: /opt/pulsar/conf/zookeeper.conf
    mode: '0644'
  notify: restart zookeeper

- name: Configure ZooKeeper environment
  template:
    src: zookeeper_env.sh.j2
    dest: /opt/pulsar/conf/zookeeper_env.sh
    mode: '0755'
  notify: restart zookeeper

- name: Create ZooKeeper systemd service
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    mode: '0644'
  notify:
    - reload systemd
    - restart zookeeper

- name: Enable and start ZooKeeper
  systemd:
    name: zookeeper
    enabled: yes
    state: started
