---
# BookKeeper Default Variables

pulsar_version: "3.0.0"

bookkeeper_heap_size: "768M"
bookkeeper_direct_memory_size: "512M"
bookkeeper_journal_dir: "/mnt/bookkeeper/journal"
bookkeeper_ledger_dirs:
  - "/mnt/bookkeeper/ledgers"
bookkeeper_journal_max_size_mb: 2048
bookkeeper_journal_sync_data: true
bookkeeper_ledger_storage_class: "org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage"
bookkeeper_num_journal_callback_threads: 4
bookkeeper_num_add_worker_threads: 4
