---
# ZooKeeper Default Variables

pulsar_version: "3.0.0"
pulsar_cluster_name: "pulsar-aws-lab"

zookeeper_heap_size: "512M"
zookeeper_max_client_connections: 60
zookeeper_tick_time: 2000
zookeeper_init_limit: 10
zookeeper_sync_limit: 5
zookeeper_data_dir: "/var/lib/zookeeper"
